services:
  opencode:
    build: .
    stdin_open: true
    tty: true
    command: /root/.opencode/bin/opencode
    container_name: opencode
    volumes:
      - ./app:/app/
      - ./.config:/home/opencode/.config
  opencode-web:
    build: .
    stdin_open: true
    tty: true
    command: /root/.opencode/bin/opencode web --port 4096
    container_name: opencode
    ports:
      - 4096:4096
    volumes:
      - ./app:/app/
      - ./.config:/home/opencode/.config
  